### ISSUE TITLE
uncaught (in promise) SyntaxError: Unexpected token C in JSON at position 0

### ISSUE THREAD

**Issue by mohammed-najeeb** [aisensiy/react-survey#1]

**Comment by mohammed-najeeb** [comment]
Uncaught (in promise) SyntaxError: Unexpected token C in JSON at position 0
    at JSON.parse (<anonymous>)
    at _axios2.default.create.transformResponse (index.js:32)
    at transform (transformData.js:16)
    at Object.forEach (utils.js:221)
    at transformData (transformData.js:15)
    at onRejected (dispatchRequest.js:66)

**Comment by theWando** [comment]
Actually it fails because the api /users does not exists.
![captura de pantalla de 2017-03-21 13-06-01](https://cloud.githubusercontent.com/assets/9989669/24157124/41686e14-0e37-11e7-9bea-35f1d17b744f.png)

**Comment by aisensiy** [comment]
Because the default backend `http://localhost:3000` does not exist. 

Here is the backend I use for the online demo: [https://github.com/aisensiy/react-survey-backend](https://github.com/aisensiy/react-survey-backend)
