### ISSUE TITLE
What i need to change in the code to use my Heroku Backend?

### ISSUE THREAD

**Issue by GunnerStraiker1** [aisensiy/react-survey#5]
I clone the backend repo and put it in a heroku app, but i don´t know what i need to change in the code to works perfectly

**Comment by miranaitamara** [comment]
Hello @GunnerStraiker1 ,

When I implement our code [react-survey-backend](https://github.com/aisensiy/react-survey-backend) I have this issue 
`(Error: Unable to compile JSON schema for post /authentication: Unexpected token L in JSON at position 0) 
`
I can't fix it !!

Best Regards
